version: '3'

services:

  #
  # mysql service
  #
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - persistent:/var/lib/mysql

  #
  # phpmyadmin service
  #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  #
  # apache php service service
  #
  web:
    build: ./apache
    container_name: ${PROJECT_NAME}_web
    shm_size: '2gb'
    ports:
      - "8888:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
    depends_on:
      - db
#
# volumes
#
volumes:
  persistent:
